const express = require('express');
const { createServer } = require('http');
const { join } = require('path');
const { Server } = require('socket.io');
const { exec } = require('child_process');
const bodyParser = require('body-parser');

require('dotenv').config();

const app = express();
const PORT = process.env.PORT || 5500;

const server = createServer(app);
const io = new Server(server);

app.use(express.static('public'));
app.use(bodyParser.json());

let replicateApiKey = '';
let openaiApiKey = '';

io.on('connection', (socket) => {
    console.log('A user connected');

    // Listen for the submission of API keys
    socket.on('submit api keys', (data) => {
        console.log('API Keys received:', data);
        replicateApiKey = data.replicateApiKey;
        openaiApiKey = data.openaiApiKey;
    });

    socket.on('submit title', (data) => {
        const command = `python3 generate_title.py "${data}" "${openaiApiKey}"`;
        exec(command, (error, stdout, stderr) => {
            if (error || stderr) {
                console.error('Error executing Python script:', error || stderr);
                io.emit('error', 'Failed to generate title');
                return;
            }
            try {
                const result = JSON.parse(stdout.trim());
                if (result.error) {
                    io.emit('error', result.error);
                } else {
                    io.emit('new title', result.title);
                    console.log("Title generated by AI:", result.title);
                }
            } catch (e) {
                console.error('Error parsing Python output:', e);
                io.emit('error', 'Failed to parse title generation output');
            }
        });
    });

    socket.on('submit bio', (data) => {
        const { name, bio } = data;
        const command = `python3 generate_bio.py "${name}" "${bio}" "${openaiApiKey}"`;
        exec(command, (error, stdout, stderr) => {
            if (error || stderr) {
                console.error('Error executing Python script:', error || stderr);
                io.emit('error', 'Failed to generate bio');
                return;
            }
            try {
                const result = JSON.parse(stdout.trim());
                if (result.error) {
                    io.emit('error', result.error);
                } else {
                    io.emit('new bio', result.bio);
                    console.log("Bio:", result.bio);
                }
            } catch (e) {
                console.error('Error parsing Python output:', e);
                io.emit('error', 'Failed to parse bio generation output');
            }
        });
    });

    socket.on('submit header', (data) => {
        io.emit('new header', data);
    });

    socket.on('submit chat', (data) => {
        io.emit('new chat', data);
    });

    socket.on('submit label', (data) => {
        const command = `python3 generate_label.py "${data}" "${openaiApiKey}"`;
        exec(command, (error, stdout, stderr) => {
            if (error || stderr) {
                console.error('Error executing Python script:', error || stderr);
                io.emit('error', 'Failed to generate label');
                return;
            }
            try {
                const result = JSON.parse(stdout.trim());
                if (result.error) {
                    io.emit('error', result.error);
                } else {
                    io.emit('new label', result.title);
                    console.log("Label:", result.title);
                }
            } catch (e) {
                console.error('Error parsing Python output:', e);
                io.emit('error', 'Failed to parse label generation output');
            }
        });
    });

    socket.on('submit concept', (prompt) => {
        const { theme, imagery } = prompt;
        
        const command_idea = `python3 generate_conceptualart.py "${theme}" "${imagery}" "${replicateApiKey}" "${openaiApiKey}"`;
        const command_idea2 = `python3 generate_conceptualart2.py "${theme}" "${imagery}" "${replicateApiKey}" "${openaiApiKey}"`;

        // First image generation
        exec(command_idea, (error, stdout, stderr) => {
            if (error || stderr) {
                console.error('Error executing Python script:', error || stderr);
                io.emit('error', 'Failed to generate first image');
                return;
            }
            
            try {
                const result = JSON.parse(stdout.trim());
                if (result.error) {
                    io.emit('error', result.error);
                } else {
                    io.emit('new image', result.url);
                    io.emit('new description', result.description);
                    io.emit("new label and article title", result.title);
                }
            } catch (e) {
                console.error('Error processing output:', e);
                io.emit('error', 'Error processing first image data');
            }
        });

        // Second image generation
        exec(command_idea2, (error, stdout, stderr) => {
            if (error || stderr) {
                console.error('Error executing Python script:', error || stderr);
                io.emit('error', 'Failed to generate second image');
                return;
            }
            try {
                const result = JSON.parse(stdout.trim());
                if (result.error) {
                    io.emit('error', result.error);
                } else {
                    io.emit('new image 2', result.url);
                }
            } catch (e) {
                console.error('Error processing output:', e);
                io.emit('error', 'Error processing second image data');
            }
        });
    });
});

app.get('/', (req, res) => {
    res.sendFile(join(__dirname, 'public/home.html'));
});

server.listen(PORT, () => {
    console.log(`Server running at http://localhost:${PORT}`);
});